### ISSUE TITLE
Is 85% OTU clustering needed for ONT?

### ISSUE THREAD

**Issue by m-ocejo** [DeniRibicic/q2ONT#7]
Dear Deni,
thank you for developing this tool. We have used it to analyse a dataset but were quite surprised to see so little difference between healty and diseased samples. I am new to 16S metabarcoding using nanopore and have so many doubts.
I understand that ONT have higher error rates than Illumina but in my humble opinion, I think that 85% OTU clustering was way too low. Could the little differences between samples be affected by this? Trying to figure this out from literature, I find that in many cases, researchers do direct taxonomic classification without the OTU clustering step (I infer this, since no OTU clustering step was mentioned, so I may as well be in the wrong). I was wondering if the clustering is really needed in the analysis of full-length 16SrRNA gene, since the number of reads produced with this technology is much lower compared to Illumina.

All the best,

M

**Comment by DeniRibicic** [comment]
Hi,

This tool was developed some years ago, when there was no available options, or very limited ones, to sequence and analyse full 16S rRNA amplicons generated by ONT. At the time there were few papers suggesting using OTU approach with a much lower threshold for clustering than what is usually applied on NGS data (>97%) due, as you mentioned, higher error rate (15%). Obviously, this has downsides. The pipeline has not been updated since then, and there are some other options available now which will produce far better output, e.g., https://github.com/Saskia-Oosterbroek/decona. 
This tool e.g., will cluster and polish your reads, and create a consensus sequence (given enough seq. depth), which you can use to assign taxonomy on it. It is a different approach compared to classic OTU clustering, as it uses CD-hit for it (not read alignment based, but uses short word tables).
Alternatively, you can also use the q2ONT and put the threshold in the code to be 1, that way, each sequence will be treated as a separate OTU, which in the end will result that each read will get its own taxonomic annotation. However this will be computationally more intensive, and might crash if you do not have a lot of RAM.

Hope this helps.

**Comment by m-ocejo** [comment]
Thank you so much for your helpful reply!
